name: ericmichaeltollefson.photography
favicon: null
layout_spectrum: 0.25681
typography_spectrum: 0.60422
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d9e9ff'
    - '#aabcd2'
    - '#8597ad'
    - '#536069'
    - '#101012'
  brandStrength: 0
  lightness: 0.125
  saturation: 0.0625
  rhythmicContrast: 0
purpose: []
